### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by tkwonn** [Amiibo-Atlas/Amiibo-Atlas#48]
Quick question about the landing page.

Our entry point currently uses the `Splash.tsx` component. In PR #46, I renamed it to `App.tsx` since it's commonly used as the entry point.

Is this supposed to be the entry point (landing page) of our app, or is it just a temporary thing? `Home.tsx` also appears to function like an entry point, so I'm a bit confused. If Splash.tsx is temporary, perhaps we could move the contents of Home.tsx into App.tsx and delete what we currently have in the `/` route. What do you think?

Also, regarding the landing page ideas @AriZeto mentioned on Discord, these sites might help get some ideas
- [link1](https://www.nintendo.com/en-gb/Hardware/amiibo-/About-amiibo/About-amiibo-932316.html#:~:text=amiibo%20are%20interactive%20figures%20and,ll%20uncover%20surprising%20new%20features!)
- [link2](https://store.nintendo.co.uk/en)

I think adding "What are amiibo?" and a quick intro about what users can do on our site would be helpful.

**Comment by AriZeto** [comment]
Ideally, it was supposed to be an entry point - yes. 

I'll take a look into that, no worries. 

We can make Home.tsx the `/` route again. The contents in Home.tsx can stay the same. We can rename this file to app.tsx.

A "What are amiibo" page is not a bad idea. Thank you.
