### ISSUE TITLE
Wishlist Issue

### ISSUE THREAD

**Issue by tkwonn** [Amiibo-Atlas/Amiibo-Atlas#59]
There are still a few issues that need to be addressed:

- [x] Users can add the same amiibo to their wishlist multiple times (duplicate wishlist)
- [x] There is no indication on the /amiibos page that a user has already added a specific amiibo to their wishlist. Need a clear UI where the heart icon turns red when an amiibo is added to the Wishlist and remains colorless if not.

**Comment by tkwonn** [comment]
![Screenshot 2024-05-16 at 13 42 31](https://github.com/Amiibo-Atlas/Amiibo-Atlas/assets/66197642/ccdd2269-060b-4578-bcb5-4ebdae2d356f)
![Screenshot 2024-05-16 at 13 42 18](https://github.com/Amiibo-Atlas/Amiibo-Atlas/assets/66197642/9c688e1a-a715-4bc5-b86b-d942661e9aed)

**Comment by paka16** [comment]
#62 
This PR tries to solve the second task!

**Comment by AriZeto** [comment]
Both issues have been resolved. Closing.
