### ISSUE TITLE
Amiibo Param page 

### ISSUE THREAD

**Issue by tkwonn** [Amiibo-Atlas/Amiibo-Atlas#64]
- [x] Improve UI for /amiibos/:amiiboId page. currently, we need to scroll all the way down to see the information. It might be a good idea to show three similar Amiibo recommendations instead, just like this [website](https://store.nintendo.co.uk/en/noah-and-mio-double-pack-amiibo-000000000010011646) does.

**Comment by AriZeto** [comment]
@jckim014 Took care of this.
